hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
cxc:
  easemob:
    clientId: YXA6Umv1ME80EeeUBzUFTdHW7g
    clientSecret: YXA6AVAIDbjFO7Q3QsaiGUZIbD2EEZE
    tokenUrl: https://a1.easemob.com/fanqilong/cxc/token
    userUrl: https://a1.easemob.com/fanqilong/cxc/users
  log:
    level: DEBUG
redis: 
  token: 815989761215415db597670ba2e32ef1
spring:
  zipkin.base-url: 'http://47.93.54.230:9411'
  datasource:
    name: college
    username: root
    password: Wangdachui#520
    url: jdbc:mysql://47.93.54.230:3306/collage?useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 10
    tomcat:
      max-idle: 20
      min-idle: 6
      max-active: 25
mongodb:
  host: 47.93.54.230
  port: 8074
  name: college